type = "Education"
title = "Education"

[profile]
research_interests = [
  "Flexible/Wearable Electronics", "Bio-Integrated Electronics", "Electrochemical biosensors", "2D material synthesis", "Multiscale Biointerfaces", "Tissue Engineering" , "Electrochemistry", "Energy Harvesting Devices"
]

[[sections]]
id = "Education"
type = "markdown"
source = "Education.md"
title = "About"


[[sections]]
id = "Honors and Awards"
type = "list"
title = "Honors and Awards"
source = "Honors and Awards"

