title = "Main"
type = "main"

[profile]
research_interests = [
  "Flexible/Wearable Electronics",
  "Bio-Integrated Electronics",
  "Electrochemical biosensors",
  "2D material synthesis",
  "Multiscale Biointerfaces",
  "Tissue Engineering",
]

[[sections]]
id = "Research experince"
type = "markdown"
title = "Research experince"
source = "Research experince.md"


[[sections]]
id = "Education"
type = "markdown"
title = "Education"
source = "Education.md"

[[sections]]
id = "Honors and Awards"
type = "markdown"
title = "Honors and Awards"
source = "Honors and Awards.md"
